sudo: required
services:
  - docker

before_install:
  - docker build -t leehj8687/docker-react -f Dockerfile.dev .

# the script section is supposed to contain all the different commands that
# need to be exectued to actually run our test suite.
script:
  - docker run -e CI=true leehj8687/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "test_docker_react"
  env: "TestDockerReact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-484222649392"
  bucket_path: "test_docker_react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key : $AWS_SECRET_KEY